disabled_worlds:
  - "duels"
  - "another_world"

utilities:
  enchanted_golden_apple_recipe: true

logs:
  enable: true
  cause: true
  inventory: true

dps_feature:
  entity_type: "SKELETON"
  name: "DPS"
  location:

command_blacklist:
  - "duel"

anti_pearl:
  enable: true
  blacklist_materials:
  - CARPET
  - BED
  - SLAB
  - STAIRS
  - HOPPER




