main: com.ar.askgaming.pvpthings.PvpThings
name: PvpThings
version: 1.0
author: AskGaming
api-version: 1.21
description: A plugin that adds some pvp features to the game.
commands:
  pvp:
    permission: pvpthings.pvp
  contract:
    permission: pvpthings.contract
    aliases: [bounty,contracts]
